name: Linter

on:
  push:
    branches:
      - main
      - 'dev-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8
          python -m pip install --upgrade pip
      - name: Check flake8
        run: python -m flake8 .
