name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            dist/*.whl
            dist/*.tar.gz
          body: |
            ## Changes in v${{ steps.version.outputs.version }}
            
            This release was automatically generated from tag `v${{ steps.version.outputs.version }}`.
            
            ### Package Files
            - **Wheel**: `dist/*.whl` - Install with `pip install <wheel-file>`
            - **Source**: `dist/*.tar.gz` - Source distribution
            
            ### Installation
            ```bash
            pip install MyHelloWorldProject==${{ steps.version.outputs.version }}
            ```
            
            ### Usage
            ```python
            import hello_world
            hello_world.say_hello()
            print(f"Version: {hello_world.get_version()}")
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}