name: Test

on:
  push:
    branches:
      - main
      - 'dev-**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests with tox
        run: tox
      - name: Checking package installation
        run: pip install .
