name: test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
        python -m pip install -r requirements.txt
        python -m pip install flake8
      - name: Check flake8
        run: python -m flake8 .
      - name: Run tests
        run: python -m unittest discover tests
