name: Test

on:
  push:
    branches:
      - main
      - 'dev-**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python versions
        uses: actions/setup-python@v2
        with:
          python-version: |
            3.8
            3.10
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests with tox
        run: tox
      - name: Checking package installation
        run: pip install .
